Add --version option to print frontend and backend (if enabled) and exit. Add check if backend exists.

diff --git a/astroberry-push b/astroberry-push
--- a/astroberry-push
+++ b/astroberry-push
@@ -26,9 +26,11 @@
 #   <message> is the notification message
 #   <priority> it one of: verbose, info, warn, error. If omitted defaults to warn.
 
+VERSION="1.0"
+
 print_usage() {
   echo SYNOPSIS
-  echo "  $0 <module> <message> [priority]"
+  echo "  $0 ( --version | <module> <message> [priority] )"
   echo
 }
 
@@ -36,25 +38,29 @@ CONFIG_DIR="/etc/astroberry-push"
 CONFIG_FILE="$CONFIG_DIR/push.conf"
 BACKENDS_DIR="/usr/share/astroberry-push/backends"
 
+min_priority_level=warn
+
+[ -e "$CONFIG_FILE" ] || { echo >&2 "ERROR: missing config file '$CONFIG_FILE'"; exit 1; }
+
+[ "$1" = "--version" ] && echo "Astroberry-Push version $VERSION"
+
+source $CONFIG_DIR/push.conf
+[ "$backend" = "none" -o "$backend" = "" ] && exit 0
+
+[ -f $BACKENDS_DIR/$backend/backend.sh ] || { echo >&2 "ERROR: backend '$backend' not found. Check backend installation."; exit 1; }
+source $BACKENDS_DIR/$backend/backend.sh
+
+if [ "$1" = "--version" ]; then
+  echo "Backend '$backend' version $BACKEND_VERSION"
+  exit 0
+fi
+
 if [ $# -lt 2 ]; then
   echo "ERROR: missing argument" 1>&2
   print_usage
   exit 1
 fi
 
-min_priority_level=warn
-
-if [ ! -e "$CONFIG_FILE" ]; then
-    echo "ERROR: missing config file 'CONFIG_FILE'" 1>&2
-    exit 1
-fi
-
-source $CONFIG_DIR/push.conf
-if [ "$backend" = "none" -o "$backend" = "" ]; then
-  exit 0
-fi
-
-source $BACKENDS_DIR/$backend/backend.sh
 
 case "$3" in
   "verbose")
